# Generated by Django 3.2 on 2021-09-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_twofatoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofatoken',
            name='verification_code',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
