# Generated by Django 3.2 on 2021-09-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_twofatoken_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofatoken',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
