# Generated by Django 3.2 on 2021-09-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_resettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
