# Generated by Django 3.2 on 2021-12-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(default='https://res.cloudinary.com/do7imvim7/image/upload/v1640112764/bote/profile_images/default_updfcj.jpg'),
        ),
    ]
