# Generated by Django 3.2 on 2021-09-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='room_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('individual', 'individual'), ('group', 'group')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('image', 'image'), ('text', 'text'), ('document', 'document'), ('audio', 'audio'), ('video', 'video')], default='text', max_length=20),
        ),
    ]
