# Generated by Django 3.2 on 2021-09-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210904_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('video', 'video'), ('audio', 'audio'), ('image', 'image'), ('text', 'text'), ('document', 'document')], default='text', max_length=20),
        ),
    ]
