# Generated by Django 3.2 on 2021-09-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210913_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('group', 'group'), ('individual', 'individual')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('video', 'video'), ('document', 'document'), ('audio', 'audio'), ('image', 'image'), ('text', 'text')], default='text', max_length=20),
        ),
    ]
