# Generated by Django 3.2 on 2021-09-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210913_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('individual', 'individual'), ('group', 'group')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('text', 'text'), ('document', 'document'), ('video', 'video'), ('audio', 'audio'), ('image', 'image')], default='text', max_length=20),
        ),
    ]
