# Generated by Django 3.2 on 2021-09-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210913_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('audio', 'audio'), ('video', 'video'), ('image', 'image'), ('document', 'document'), ('text', 'text')], default='text', max_length=20),
        ),
    ]
