# Generated by Django 3.2 on 2021-09-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_messages_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('group', 'group'), ('individual', 'individual')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('text', 'text'), ('document', 'document'), ('image', 'image'), ('audio', 'audio'), ('video', 'video')], default='text', max_length=20),
        ),
    ]
