# Generated by Django 3.2 on 2021-09-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210916_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('video', 'video'), ('document', 'document'), ('text', 'text'), ('image', 'image'), ('audio', 'audio')], default='text', max_length=20),
        ),
    ]
