# Generated by Django 3.2 on 2021-09-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_messages_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('individual', 'individual'), ('group', 'group')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('image', 'image'), ('audio', 'audio'), ('text', 'text'), ('document', 'document'), ('video', 'video')], default='text', max_length=20),
        ),
    ]
