# Generated by Django 3.2 on 2021-09-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20210916_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('video', 'video'), ('text', 'text'), ('document', 'document'), ('image', 'image'), ('audio', 'audio')], default='text', max_length=20),
        ),
    ]
