# Generated by Django 3.2 on 2021-10-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20210929_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('individual', 'individual'), ('group', 'group')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('video', 'video'), ('text', 'text'), ('document', 'document'), ('audio', 'audio'), ('image', 'image')], default='text', max_length=20),
        ),
    ]
