# Generated by Django 3.2 on 2021-12-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20211001_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('video', 'video'), ('image', 'image'), ('audio', 'audio'), ('document', 'document'), ('text', 'text')], default='text', max_length=20),
        ),
    ]
