# Generated by Django 3.2 on 2021-12-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_messages_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('group', 'group'), ('individual', 'individual')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('document', 'document'), ('video', 'video'), ('text', 'text'), ('audio', 'audio'), ('image', 'image')], default='text', max_length=20),
        ),
    ]
